=== TripSit/drugs/schemas/drug-schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "Drug",
  "type": "object",
  "additionalProperties": false,
  "required": ["name", "pretty_name", "properties"],
  "properties": {
    "aliases": { "type": "array", "items": { "type": "string" } },
    "categories": { "type": "array", "items": { "$ref": "#/definitions/Category" } },
    "formatted_aftereffects": { "$ref": "#/definitions/Duration" },
    "formatted_dose": { "$ref": "#/definitions/Dose" },
    "formatted_duration": { "$ref": "#/definitions/Duration" },
    "formatted_effects": { "type": "array", "items": { "type": "string" } },
    "formatted_onset": { "$ref": "#/definitions/Duration" },
    "links": { "$ref": "#/definitions/Links" },
    "name": { "type": "string" },
    "pretty_name": { "type": "string" },
    "properties": { "$ref": "#/definitions/Properties" },
    "pweffects": { "type": "object", "additionalProperties": { "type": "string", "format": "uri" } },
    "dose_note": { "type": "string" },
    "sources": { "$ref": "#/definitions/Sources" }
  },
  "definitions": {
    "Category": {
      "type": "string",
      "enum": ["depressant","habit-forming","tentative","research-chemical","psychedelic","stimulant","dissociative","inactive","empathogen","common","benzodiazepine","opioid","supplement","nootropic","barbiturate","deliriant","ssri"],
      "title": "Category"
    },
    "Dose": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "Oral": { "$ref": "#/definitions/Dosage" },
        "Insufflated": { "$ref": "#/definitions/Dosage" },
        "Rectal": { "$ref": "#/definitions/Dosage" },
        "Vapourized": { "$ref": "#/definitions/Dosage" },
        "Intravenous": { "$ref": "#/definitions/Dosage" },
        "Smoked": { "$ref": "#/definitions/Dosage" },
        "Sublingual": { "$ref": "#/definitions/Dosage" },
        "Buccal": { "$ref": "#/definitions/Dosage" },
        "Intramuscular": { "$ref": "#/definitions/Dosage" },
        "Transdermal": { "$ref": "#/definitions/Dosage" },
        "HBWR": { "$ref": "#/definitions/Dosage" },
        "Morning_Glory": { "$ref": "#/definitions/Dosage" },
        "Dried": { "$ref": "#/definitions/Dosage" },
        "Fresh": { "$ref": "#/definitions/Dosage" },
        "Insufflated(Pure)": { "$ref": "#/definitions/Dosage" },
        "Oral(Benzedrex)": { "$ref": "#/definitions/Dosage" },
        "Oral(Pure)": { "$ref": "#/definitions/Dosage" },
        "Dry": { "$ref": "#/definitions/Dosage" },
        "Wet": { "$ref": "#/definitions/Dosage" }
      },
      "title": "Dose"
    },
    "Dosage": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "Common": { "type": "string" },
        "Light": { "type": "string" },
        "Strong": { "type": "string" },
        "Threshold": { "type": "string" },
        "Heavy": { "type": "string" },
        "Dangerous": { "type": "string" },
        "Fatal": { "type": "string" },
        "Note": { "type": "string" }
      },
      "title": "Dosage"
    },
    "Duration": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "_unit": { "$ref": "#/definitions/Unit" },
        "value": { "type": "string" },
        "Insufflated": { "type": "string" },
        "Oral": { "type": "string" },
        "Rectal": { "type": "string" },
        "Vapourized": { "type": "string" },
        "Smoked": { "type": "string" },
        "Oral_ER": { "type": "string" },
        "Oral_IR": { "type": "string" },
        "Intramuscular": { "type": "string" },
        "Intravenous": { "type": "string" },
        "Metabolites": { "type": "string" },
        "Parent": { "type": "string" },
        "Oral_MAOI": { "type": "string" },
        "Buccal": { "type": "string" },
        "Transdermal": { "type": "string" },
        "Sublingual": { "type": "string" },
        "Insufflated_IR": { "type": "string" },
        "Insufflated_XR": { "type": "string" }
      },
      "title": "Duration"
    },
    "Links": {
      "type": "object",
      "additionalProperties": false,
      "required": ["experiences"],
      "properties": {
        "experiences": { "type": "string", "format": "uri" },
        "pihkal": { "type": "string", "format": "uri" },
        "tihkal": { "type": "string", "format": "uri" }
      },
      "title": "Links"
    },
    "Properties": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "after-effects": { "type": "string" },
        "aliases": { "type": "array", "items": { "type": "string" } },
        "avoid": { "type": "string" },
        "categories": { "type": "array", "items": { "$ref": "#/definitions/Category" } },
        "dose": { "type": "string" },
        "duration": { "type": "string" },
        "half-life": { "type": "string" },
        "onset": { "type": "string" },
        "summary": { "type": "string" },
        "test-kits": { "type": "string" },
        "experiences": { "type": "string", "format": "uri" },
        "warning": { "type": "string" },
        "marquis": { "type": "string" },
        "effects": { "type": "string" },
        "risks": { "type": "string" },
        "comeup": { "type": "string" },
        "note": { "type": "string" },
        "detection": { "type": "string" },
        "wiki": { "type": "string", "format": "uri" },
        "mdma": { "type": "string" },
        "tolerance": { "type": "string" },
        "bioavailability": { "type": "string" },
        "dose_to_diazepam": { "type": "string" },
        "adverse-effects": { "type": "string" },
        "chemistry": { "type": "string" },
        "contraindications": { "type": "string" },
        "legal": { "type": "string" },
        "overdose-symptoms": { "type": "string" },
        "pharmacokinetics": { "type": "string" },
        "pharmacology": { "type": "string" },
        "obtain": { "type": "string" },
        "pharmacodynamics": { "type": "string" },
        "side-effects": { "type": "string" },
        "molecule": { "type": "string", "format": "uri" },
        "vaporization": { "type": "string" },
        "calculator": { "type": "string", "format": "uri" },
        "chart": { "type": "string", "format": "uri" },
        "Oral": { "type": "string" },
        "general-advice": { "type": "string" },
        "potentiators": { "type": "string" }
      },
      "title": "Properties"
    },
    "Sources": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "_general": { "type": "array", "items": { "type": "string" } },
        "dose": { "type": "array", "items": { "type": "string", "format": "uri" } },
        "duration": { "type": "array", "items": { "type": "string", "format": "uri" } },
        "bioavailability": { "type": "array", "items": { "type": "string", "format": "uri" } },
        "legality": { "type": "array", "items": { "type": "string", "format": "uri" } },
        "onset": { "type": "array", "items": { "type": "string" } }
      },
      "title": "Sources"
    },
    "Unit": {
      "type": "string",
      "enum": ["hours", "minutes"],
      "title": "Unit"
    }
  }
}

=== TripSit/drugs/src/data/theobromine.json
{
  "formatted_dose": {
    "Oral": {
      "Common": "200-300mg",
      "Heavy": "600mg+",
      "Light": "100-200mg",
      "Strong": "300-600mg"
    }
  },
  "formatted_duration": {
    "_unit": "hours",
    "value": "30-40"
  },
  "formatted_effects": [
    "elevated heart rate",
    "vasodilation",
    "sweating",
    "trembling",
    "headaches"
  ],
  "formatted_onset": {
    "_unit": "hours",
    "value": "2-3"
  },
  "name": "theobromine",
  "pretty_name": "Theobromine",
  "properties": {
    "dose": "Light: 100-200mg Common: 200-300mg Strong: 300-600mg Heavy: 600mg+",
    "duration": "onset: 30-40 minutes duration: 7-12 hours after-effects: 5-12 hours",
    "effects": "elevated heart rate, vasodilation, sweating, trembling, headaches",
    "onset": "2-3 hours.",
    "summary": "Theobromine is the principal bitter alkaloid of the cacao bean. It has been used in various pharmaceutical products as a vasodilator, diuretic, and heart stimulant. Theobromine is consumed in cocoa, chocolate, and in various forms of chocolate-based foods. It is also present in small amounts in green coffee beans, tea, mate, and kola nut."
  }
}

=== TripSit/drugs/src/data/1p-eth-lad.json
{
  "aliases": [
    "1pethlad"
  ],
  "categories": [
    "psychedelic",
    "tentative",
    "research-chemical"
  ],
  "dose_note": " NOTE: These doses are very tentative, and are based on the likelihood that the dosage profile will be similar to ETH-LAD.",
  "formatted_aftereffects": {
    "_unit": "hours",
    "value": "2-12"
  },
  "formatted_dose": {
    "Oral": {
      "Common": "60-100ug",
      "Light": "30-60ug",
      "Strong": "100-200ug+",
      "Threshold": "20-30ug"
    }
  },
  "formatted_duration": {
    "_unit": "hours",
    "value": "6-10"
  },
  "formatted_onset": {
    "_unit": "minutes",
    "value": "15-90"
  },
  "name": "1p-eth-lad",
  "pretty_name": "1P-ETH-LAD",
  "properties": {
    "after-effects": "2-12 hours.",
    "aliases": [
      "1pethlad"
    ],
    "categories": [
      "psychedelic",
      "tentative",
      "research-chemical"
    ],
    "dose": "Oral Threshold: 20-30ug Light: 30-60ug Common: 60-100ug Strong: 100-200ug+ | NOTE: These doses are very tentative, and are based on the likelihood that the dosage profile will be similar to ETH-LAD.",
    "duration": "6-10 hours.",
    "experiences": "https://erowid.org/experiences/subs/exp_1PETHLAD.shtml",
    "onset": "15-90 minutes",
    "summary": "A new psychedelic lysergamide which is suspected to be a prodrug of ETH-LAD, which could explain why the doses are very similar, it alternatively could be active on its own. There are no studies on it currently."
  }
}

=== TripSit/drugs/src/data/methadone.json
{
  "categories": [
    "opioid",
    "habit-forming",
    "depressant",
    "common"
  ],
  "formatted_aftereffects": {
    "_unit": "hours",
    "value": "1-48"
  },
  "formatted_dose": {
    "Oral": {
      "Common": "10-20mg",
      "Light": "5-10mg",
      "Strong": "20-35mg+"
    }
  },
  "formatted_duration": {
    "_unit": "hours"
  },
  "formatted_effects": [
    "Euphoria",
    "Dry Mouth",
    "Mood lift",
    "Itchiness",
    "Relaxant",
    "Constipation",
    "Pupil constriction",
    "Analgesia"
  ],
  "formatted_onset": {
    "_unit": "minutes",
    "value": "45-120"
  },
  "links": {
    "experiences": "https://www.erowid.org/experiences/subs/exp_Methadone.shtml"
  },
  "name": "methadone",
  "pretty_name": "Methadone",
  "properties": {
    "after-effects": "1-48 hours.",
    "avoid": "All other CNS depressants.",
    "bioavailability": "Oral 70-90% | Rectal (aqueous liquid) ~80%",
    "categories": [
      "opioid",
      "habit-forming",
      "depressant",
      "common"
    ],
    "dose": "Light: 5-10mg Common: 10-20mg Strong: 20-35mg+ NOTE: these doses are not intended for opioid naïve users. 30mg could be lethal for an opioid naïve user. Please note opioid naïve refers to recent usage, not opioid experience. It is recommended, as always, to start low and increase dosage /slowly/",
    "duration": "Oral 6-12 hours. NOTE: The duration may last much longer depending on a variety of factors, such as physical and mental drug dependence.",
    "effects": "Euphoria, Dry Mouth, Mood lift, Itchiness, Relaxant, Constipation, Pupil constriction, Analgesia.",
    "half-life": "12-18 hours on the first dose 13-47 on concurrent",
    "onset": "45-120 minutes.",
    "summary": "An opioid drug used as an analgesic and is often used during detoxification of other opioids. There are a variety of reasons for this such as methadone's longer half-life duration."
  },
  "sources": {
    "_general": [
      "Methadone trials have proven successful in treating Heroin addiction - http://jamanetwork.com/journals/jama/article-abstract/656315",
      "Pharmacogenetics of chronic pain management - https://doi.org/10.1016/j.clinbiochem.2014.05.065"
    ]
  }
}

=== TripSit/drugs/src/data/scopolamine.json
{
  "categories": [
    "deliriant",
    "tentative"
  ],
  "links": {
    "experiences": "https://www.erowid.org/experiences/subs/exp_Scopolamine.shtml"
  },
  "name": "scopolamine",
  "pretty_name": "Scopolamine",
  "properties": {
    "avoid": "One of the active substances in datura, caution is strongly recommended with this drug.",
    "categories": [
      "deliriant",
      "tentative"
    ],
    "summary": "The main active compound in datura. Medium and high doses may have significant negative side effects and can cause extreme deliriant hallucinations. Caution is strongly recommended."
  },
  "pweffects": {
    "Abnormal heartbeat": "https://psychonautwiki.org/wiki/Abnormal_heartbeat",
    "Acuity suppression": "https://psychonautwiki.org/wiki/Acuity_suppression",
    "After images": "https://psychonautwiki.org/wiki/After_images",
    "Amnesia": "https://psychonautwiki.org/wiki/Amnesia",
    "Anxiety": "https://psychonautwiki.org/wiki/Anxiety",
    "Auditory enhancement": "https://psychonautwiki.org/wiki/Auditory_enhancement",
    "Auditory hallucinations": "https://psychonautwiki.org/wiki/Auditory_hallucinations",
    "Autonomous entities": "https://psychonautwiki.org/wiki/Autonomous_entities",
    "Cognitive dysphoria": "https://psychonautwiki.org/wiki/Cognitive_dysphoria",
    "Depression": "https://psychonautwiki.org/wiki/Depression",
    "Difficulty urinating": "https://psychonautwiki.org/wiki/Difficulty_urinating",
    "Dizziness": "https://psychonautwiki.org/wiki/Dizziness",
    "Dream potentiation": "https://psychonautwiki.org/wiki/Dream_potentiation",
    "Drifting": "https://psychonautwiki.org/wiki/Drifting",
    "Emotion suppression": "https://psychonautwiki.org/wiki/Emotion_suppression",
    "External hallucinations": "https://psychonautwiki.org/wiki/External_hallucinations",
    "Frequent urination": "https://psychonautwiki.org/wiki/Frequent_urination",
    "Increased heart rate": "https://psychonautwiki.org/wiki/Increased_heart_rate",
    "Information processing suppression": "https://psychonautwiki.org/wiki/Information_processing_suppression",
    "Internal hallucinations": "https://psychonautwiki.org/wiki/Internal_hallucinations",
    "Language suppression": "https://psychonautwiki.org/wiki/Language_suppression",
    "Muscle cramps": "https://psychonautwiki.org/wiki/Muscle_cramps",
    "Muscle spasms": "https://psychonautwiki.org/wiki/Muscle_spasms",
    "Nausea": "https://psychonautwiki.org/wiki/Nausea",
    "Paranoia": "https://psychonautwiki.org/wiki/Paranoia",
    "Pattern recognition suppression": "https://psychonautwiki.org/wiki/Pattern_recognition_suppression",
    "Perception of increased weight": "https://psychonautwiki.org/wiki/Perception_of_increased_weight",
    "Peripheral information misinterpretation": "https://psychonautwiki.org/wiki/Peripheral_information_misinterpretation",
    "Perspective alterations": "https://psychonautwiki.org/wiki/Perspective_alterations",
    "Photophobia": "https://psychonautwiki.org/wiki/Photophobia",
    "Psychosis": "https://psychonautwiki.org/wiki/Psychosis",
    "Pupil dilation": "https://psychonautwiki.org/wiki/Pupil_dilation",
    "Restless leg syndrome": "https://psychonautwiki.org/wiki/Restless_leg_syndrome",
    "Scenarios and plots": "https://psychonautwiki.org/wiki/Scenarios_and_plots",
    "Settings, sceneries, and landscapes": "https://psychonautwiki.org/wiki/Settings,_sceneries,_and_landscapes",
    "Shadow people": "https://psychonautwiki.org/wiki/Shadow_people",
    "Spontaneous tactile sensations": "https://psychonautwiki.org/wiki/Spontaneous_tactile_sensations",
    "Thought deceleration": "https://psychonautwiki.org/wiki/Thought_deceleration",
    "Thought disorganization": "https://psychonautwiki.org/wiki/Thought_disorganization",
    "Time distortion": "https://psychonautwiki.org/wiki/Time_distortion",
    "Unspeakable horrors": "https://psychonautwiki.org/wiki/Unspeakable_horrors",
    "Vibrating vision": "https://psychonautwiki.org/wiki/Vibrating_vision",
    "Visual haze": "https://psychonautwiki.org/wiki/Visual_haze"
  }
}

=== TripSit/drugs/src/data/5-meo-dibf.json
{
  "categories": [
    "empathogen",
    "research-chemical",
    "tentative"
  ],
  "formatted_aftereffects": {
    "_unit": "hours",
    "value": "1-12"
  },
  "formatted_dose": {
    "Insufflated": {
      "Common": "10-15mg",
      "Light": "5-10mg",
      "Strong": "15-20mg+"
    },
    "Oral": {
      "Common": "20-40mg",
      "Light": "10-20mg",
      "Strong": "40-60mg+"
    }
  },
  "formatted_duration": {
    "_unit": "hours",
    "Insufflated": "6-8",
    "Oral": "8-12"
  },
  "formatted_onset": {
    "_unit": "minutes",
    "Insufflated": "5-45",
    "Oral": "20-90"
  },
  "links": {
    "experiences": "https://www.erowid.org/experiences/subs/exp_5MeODiBF.shtml"
  },
  "name": "5-meo-dibf",
  "pretty_name": "5-MeO-DIBF",
  "properties": {
    "after-effects": "1-12 hours.",
    "categories": [
      "empathogen",
      "research-chemical",
      "tentative"
    ],
    "dose": "Oral Light: 10-20mg Common: 20-40mg Strong: 40-60mg+ | Insufflated Light: 5-10mg Common: 10-15mg Strong: 15-20mg+",
    "duration": "Oral 8-12 hours. | Insufflated 6-8 hours.",
    "onset": "Oral: 20-90 minutes. | Insufflated: 5-45 minutes.",
    "summary": "The drug is related to tryptamine, it is the Benzofuran analogue of 5-MeO-DiPT. The drug is suspected to be a serotonin receptor partial agonist by some. There is limited information on this drug."
  }
}

=== TripSit/drugs/src/data/3-mmc.json
{
  "aliases": [
    "3mmc",
    "3-methylmethcathinone",
    "3methylmethcathinone",
    "3-meph",
    "3-mephedrone"
  ],
  "categories": [
    "stimulant",
    "habit-forming",
    "empathogen"
  ],
  "formatted_aftereffects": {
    "_unit": "hours",
    "value": "3-4"
  },
  "formatted_dose": {
    "Oral": {
      "Common": "75-150mg",
      "Light": "25-75mg",
      "Strong": "150mg-300mg+"
    }
  },
  "formatted_duration": {
    "_unit": "hours",
    "value": "4-7"
  },
  "formatted_effects": [
    "increased energy/alertness",
    "Decreased need for sleep",
    "Increased sociability",
    "mood lift",
    "increased libido",
    "Excessive talking",
    "Decreased appetite",
    "Weight loss",
    "Sweating",
    "Disturbed sleep patterns",
    "Bruxia",
    "Visual and auditory hallucinations",
    "Itching",
    "aggressiveness",
    "moodiness"
  ],
  "formatted_onset": {
    "_unit": "hours",
    "value": "1"
  },
  "name": "3-mmc",
  "pretty_name": "3-MMC",
  "properties": {
    "after-effects": "3-4 hours.",
    "aliases": [
      "3mmc",
      "3-methylmethcathinone",
      "3methylmethcathinone",
      "3-meph",
      "3-mephedrone"
    ],
    "categories": [
      "stimulant",
      "habit-forming",
      "empathogen"
    ],
    "dose": "Light: 25-75mg Common: 75-150mg Strong: 150mg-300mg+",
    "duration": "4-7 hours (dependent on dose/ROA/lots of stuff)",
    "effects": "increased energy/alertness, Decreased need for sleep, Increased sociability, mood lift, increased libido, Excessive talking, Decreased appetite, Weight loss, Sweating, Disturbed sleep patterns, Bruxia, Visual and Auditory hallucinations, Itching, aggressiveness, moodiness.",
    "onset": "Within an hour.",
    "summary": "A euphoric stimulant similar to mephedrone but said to lack much of the \"magic.\" Slightly less potent. Some prefer 3mmc over 4mmc due to it's more dopaminergic effects."
  }
}

=== TripSit/drugs/src/data/methaqualone.json
{
  "aliases": [
    "ludes",
    "quaaludes",
    "qualudes",
    "mandrax"
  ],
  "categories": [
    "depressant",
    "habit-forming"
  ],
  "dose_note": " NOTE: It is strongly recommended to not take greater than 300mg without a methaqualone tolerance.",
  "formatted_aftereffects": {
    "_unit": "hours",
    "value": "4-6"
  },
  "formatted_dose": {
    "Oral": {
      "Common": "150-300mg",
      "Light": "75-150mg",
      "Strong": "300mg+"
    }
  },
  "formatted_duration": {
    "_unit": "hours",
    "value": "5-8"
  },
  "formatted_effects": [
    "Anxiolytic",
    "Sedative",
    "Muscle Relaxant",
    "Amnesia",
    "Dystaxia",
    "Hypnotic"
  ],
  "formatted_onset": {
    "_unit": "minutes",
    "value": "30-45"
  },
  "links": {
    "experiences": "https://www.erowid.org/experiences/subs/exp_Methaqualone.shtml"
  },
  "name": "methaqualone",
  "pretty_name": "Methaqualone",
  "properties": {
    "after-effects": "4-6 hours.",
    "aliases": [
      "ludes",
      "quaaludes",
      "qualudes",
      "mandrax"
    ],
    "avoid": "All other CNS depressants.",
    "categories": [
      "depressant",
      "habit-forming"
    ],
    "dose": "Oral Light: 75-150mg Common: 150-300mg Strong: 300mg+ | NOTE: It is strongly recommended to not take greater than 300mg without a methaqualone tolerance.",
    "duration": "5-8 hours.",
    "effects": "Anxiolytic, Sedative, Muscle Relaxant, Amnesia, Dystaxia, Hypnotic.",
    "onset": "30-45 minutes",
    "summary": "A pharmaceutical depressant and sedative phased out due to alternative drugs becoming readily available with greater safety profiles. Part of the Qualone group of substances. The drug is considered extremely rare in all parts of the world except in South Africa, where use and abuse remain high."
  },
  "pweffects": {
    "Acuity suppression": "https://psychonautwiki.org/wiki/Acuity_suppression",
    "Anxiety suppression": "https://psychonautwiki.org/wiki/Anxiety_suppression",
    "Changes in gravity": "https://psychonautwiki.org/wiki/Changes_in_gravity",
    "Cognitive euphoria": "https://psychonautwiki.org/wiki/Cognitive_euphoria",
    "Compulsive redosing": "https://psychonautwiki.org/wiki/Compulsive_redosing",
    "Constipation": "https://psychonautwiki.org/wiki/Constipation",
    "Disinhibition": "https://psychonautwiki.org/wiki/Disinhibition",
    "Dizziness": "https://psychonautwiki.org/wiki/Dizziness",
    "Double vision": "https://psychonautwiki.org/wiki/Double_vision",
    "Dream potentiation": "https://psychonautwiki.org/wiki/Dream_potentiation",
    "Increased libido": "https://psychonautwiki.org/wiki/Increased_libido",
    "Information processing suppression": "https://psychonautwiki.org/wiki/Information_processing_suppression",
    "Internal hallucinations": "https://psychonautwiki.org/wiki/Internal_hallucinations",
    "Motor control loss": "https://psychonautwiki.org/wiki/Motor_control_loss",
    "Muscle relaxation": "https://psychonautwiki.org/wiki/Muscle_relaxation",
    "Physical euphoria": "https://psychonautwiki.org/wiki/Physical_euphoria",
    "Respiratory depression": "https://psychonautwiki.org/wiki/Respiratory_depression",
    "Sedation": "https://psychonautwiki.org/wiki/Sedation",
    "Subconscious communication": "https://psychonautwiki.org/wiki/Subconscious_communication",
    "Thought deceleration": "https://psychonautwiki.org/wiki/Thought_deceleration",
    "Visual disconnection": "https://psychonautwiki.org/wiki/Visual_disconnection"
  }
}

=== TripSit/drugs/src/data/gbl.json
{
  "categories": [
    "depressant",
    "habit-forming",
    "common"
  ],
  "dose_note": " NOTE: 1ml = 1.66 grams of GHB. Dosages above 2ml may induce heavy sleep.",
  "formatted_aftereffects": {
    "_unit": "hours",
    "value": "1-2"
  },
  "formatted_dose": {
    "Oral": {
      "Common": "0.6-1.5ml",
      "Dangerous": "5ml+",
      "Heavy": "2-3ml",
      "Light": "0.3-0.9ml",
      "Strong": "1.2-2ml"
    }
  },
  "formatted_duration": {
    "_unit": "hours",
    "value": "1-2"
  },
  "formatted_effects": [
    "relaxation",
    "mood lift",
    "happiness",
    "sociability",
    "increased sex drive",
    "lowered inhibitions",
    "analgesia",
    "dystaxia",
    "drowsiness",
    "sleep",
    "amnesia"
  ],
  "formatted_onset": {
    "_unit": "minutes",
    "value": "10-30"
  },
  "links": {
    "experiences": "https://www.erowid.org/experiences/subs/exp_GBL.shtml"
  },
  "name": "gbl",
  "pretty_name": "GBL",
  "properties": {
    "after-effects": "1-2 hours",
    "avoid": "Alcohol and other depressants.",
    "categories": [
      "depressant",
      "habit-forming",
      "common"
    ],
    "dose": "Oral Light: 0.3-0.9ml Common: 0.6-1.5ml Strong: 1.2-2ml Heavy: 2-3ml Dangerous: 5ml+ | NOTE: 1ml = 1.66g GHB. Tends to induce heavy sleep at 2ml and higher.",
    "duration": "1-2 hours",
    "effects": "relaxation, mood lift, happiness, sociability, increased sex drive, lowered inhibitions, analgesia, dystaxia, drowsiness, sleep, amnesia",
    "onset": "10-30 minutes",
    "summary": "A pro-drug to GHB whose rapid absorption leads it to have a faster onset and shorter duration."
  }
}
