=== TripSit/drugs/schemas/drug-schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "Drug",
  "type": "object",
  "additionalProperties": false,
  "required": ["name", "pretty_name", "properties"],
  "properties": {
    "aliases": { "type": "array", "items": { "type": "string" } },
    "categories": { "type": "array", "items": { "$ref": "#/definitions/Category" } },
    "formatted_aftereffects": { "$ref": "#/definitions/Duration" },
    "formatted_dose": { "$ref": "#/definitions/Dose" },
    "formatted_duration": { "$ref": "#/definitions/Duration" },
    "formatted_effects": { "type": "array", "items": { "type": "string" } },
    "formatted_onset": { "$ref": "#/definitions/Duration" },
    "links": { "$ref": "#/definitions/Links" },
    "name": { "type": "string" },
    "pretty_name": { "type": "string" },
    "properties": { "$ref": "#/definitions/Properties" },
    "pweffects": { "type": "object", "additionalProperties": { "type": "string", "format": "uri" } },
    "dose_note": { "type": "string" },
    "sources": { "$ref": "#/definitions/Sources" }
  },
  "definitions": {
    "Category": {
      "type": "string",
      "enum": ["depressant","habit-forming","tentative","research-chemical","psychedelic","stimulant","dissociative","inactive","empathogen","common","benzodiazepine","opioid","supplement","nootropic","barbiturate","deliriant","ssri"],
      "title": "Category"
    },
    "Dose": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "Oral": { "$ref": "#/definitions/Dosage" },
        "Insufflated": { "$ref": "#/definitions/Dosage" },
        "Rectal": { "$ref": "#/definitions/Dosage" },
        "Vapourized": { "$ref": "#/definitions/Dosage" },
        "Intravenous": { "$ref": "#/definitions/Dosage" },
        "Smoked": { "$ref": "#/definitions/Dosage" },
        "Sublingual": { "$ref": "#/definitions/Dosage" },
        "Buccal": { "$ref": "#/definitions/Dosage" },
        "Intramuscular": { "$ref": "#/definitions/Dosage" },
        "Transdermal": { "$ref": "#/definitions/Dosage" },
        "HBWR": { "$ref": "#/definitions/Dosage" },
        "Morning_Glory": { "$ref": "#/definitions/Dosage" },
        "Dried": { "$ref": "#/definitions/Dosage" },
        "Fresh": { "$ref": "#/definitions/Dosage" },
        "Insufflated(Pure)": { "$ref": "#/definitions/Dosage" },
        "Oral(Benzedrex)": { "$ref": "#/definitions/Dosage" },
        "Oral(Pure)": { "$ref": "#/definitions/Dosage" },
        "Dry": { "$ref": "#/definitions/Dosage" },
        "Wet": { "$ref": "#/definitions/Dosage" }
      },
      "title": "Dose"
    },
    "Dosage": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "Common": { "type": "string" },
        "Light": { "type": "string" },
        "Strong": { "type": "string" },
        "Threshold": { "type": "string" },
        "Heavy": { "type": "string" },
        "Dangerous": { "type": "string" },
        "Fatal": { "type": "string" },
        "Note": { "type": "string" }
      },
      "title": "Dosage"
    },
    "Duration": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "_unit": { "$ref": "#/definitions/Unit" },
        "value": { "type": "string" },
        "Insufflated": { "type": "string" },
        "Oral": { "type": "string" },
        "Rectal": { "type": "string" },
        "Vapourized": { "type": "string" },
        "Smoked": { "type": "string" },
        "Oral_ER": { "type": "string" },
        "Oral_IR": { "type": "string" },
        "Intramuscular": { "type": "string" },
        "Intravenous": { "type": "string" },
        "Metabolites": { "type": "string" },
        "Parent": { "type": "string" },
        "Oral_MAOI": { "type": "string" },
        "Buccal": { "type": "string" },
        "Transdermal": { "type": "string" },
        "Sublingual": { "type": "string" },
        "Insufflated_IR": { "type": "string" },
        "Insufflated_XR": { "type": "string" }
      },
      "title": "Duration"
    },
    "Links": {
      "type": "object",
      "additionalProperties": false,
      "required": ["experiences"],
      "properties": {
        "experiences": { "type": "string", "format": "uri" },
        "pihkal": { "type": "string", "format": "uri" },
        "tihkal": { "type": "string", "format": "uri" }
      },
      "title": "Links"
    },
    "Properties": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "after-effects": { "type": "string" },
        "aliases": { "type": "array", "items": { "type": "string" } },
        "avoid": { "type": "string" },
        "categories": { "type": "array", "items": { "$ref": "#/definitions/Category" } },
        "dose": { "type": "string" },
        "duration": { "type": "string" },
        "half-life": { "type": "string" },
        "onset": { "type": "string" },
        "summary": { "type": "string" },
        "test-kits": { "type": "string" },
        "experiences": { "type": "string", "format": "uri" },
        "warning": { "type": "string" },
        "marquis": { "type": "string" },
        "effects": { "type": "string" },
        "risks": { "type": "string" },
        "comeup": { "type": "string" },
        "note": { "type": "string" },
        "detection": { "type": "string" },
        "wiki": { "type": "string", "format": "uri" },
        "mdma": { "type": "string" },
        "tolerance": { "type": "string" },
        "bioavailability": { "type": "string" },
        "dose_to_diazepam": { "type": "string" },
        "adverse-effects": { "type": "string" },
        "chemistry": { "type": "string" },
        "contraindications": { "type": "string" },
        "legal": { "type": "string" },
        "overdose-symptoms": { "type": "string" },
        "pharmacokinetics": { "type": "string" },
        "pharmacology": { "type": "string" },
        "obtain": { "type": "string" },
        "pharmacodynamics": { "type": "string" },
        "side-effects": { "type": "string" },
        "molecule": { "type": "string", "format": "uri" },
        "vaporization": { "type": "string" },
        "calculator": { "type": "string", "format": "uri" },
        "chart": { "type": "string", "format": "uri" },
        "Oral": { "type": "string" },
        "general-advice": { "type": "string" },
        "potentiators": { "type": "string" }
      },
      "title": "Properties"
    },
    "Sources": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "_general": { "type": "array", "items": { "type": "string" } },
        "dose": { "type": "array", "items": { "type": "string", "format": "uri" } },
        "duration": { "type": "array", "items": { "type": "string", "format": "uri" } },
        "bioavailability": { "type": "array", "items": { "type": "string", "format": "uri" } },
        "legality": { "type": "array", "items": { "type": "string", "format": "uri" } },
        "onset": { "type": "array", "items": { "type": "string" } }
      },
      "title": "Sources"
    },
    "Unit": {
      "type": "string",
      "enum": ["hours", "minutes"],
      "title": "Unit"
    }
  }
}

=== TripSit/drugs/src/data/ept.json
{
  "aliases": [
    "ethylpropyltryptamine",
    "n,n-ethylpropyltryptamine"
  ],
  "categories": [
    "psychedelic",
    "tentative",
    "research-chemical"
  ],
  "formatted_aftereffects": {
    "_unit": "hours",
    "Insufflated": "1-4",
    "Oral": "1-6"
  },
  "formatted_dose": {
    "Oral": {
      "Common": "75-100mg",
      "Light": "50-75mg",
      "Strong": "100mg+"
    }
  },
  "formatted_duration": {
    "_unit": "hours",
    "Insufflated": "1-3",
    "Oral": "2-4"
  },
  "formatted_onset": {
    "_unit": "minutes",
    "Insufflated": "5-20",
    "Oral": "20-60"
  },
  "name": "ept",
  "pretty_name": "EPT",
  "properties": {
    "after-effects": "Oral: 1-6 hours. | Insufflated: 1-4 hours.",
    "aliases": [
      "ethylpropyltryptamine",
      "n,n-ethylpropyltryptamine"
    ],
    "categories": [
      "psychedelic",
      "tentative",
      "research-chemical"
    ],
    "dose": "Oral Light: 50-75mg Common: 75-100mg Strong: 100mg+",
    "duration": "Oral: 2-4 hours. | Insufflated: 1-3 hours.",
    "onset": "Oral: 20-60 minutes. | Insufflated: 5-20 minutes.",
    "summary": "Ethylpropyltryptamine a novel tryptamine, that is the structural homologue of DMT."
  }
}

=== TripSit/drugs/src/data/ah-7921.json
{
  "aliases": [
    "ah7921"
  ],
  "categories": [
    "opioid",
    "research-chemical",
    "habit-forming",
    "depressant"
  ],
  "formatted_aftereffects": {
    "_unit": "hours",
    "value": "1-6"
  },
  "formatted_dose": {
    "Oral": {
      "Common": "10-25mg",
      "Light": "5-10mg",
      "Strong": "25mg+"
    }
  },
  "formatted_duration": {
    "_unit": "hours",
    "Oral": "6-8",
    "Vapourized": "3-4"
  },
  "formatted_effects": [
    "Euphoria",
    "Dry Mouth",
    "Mood lift",
    "Itchiness",
    "Relaxant",
    "Constipation",
    "Pupil constriction",
    "Analgesia"
  ],
  "formatted_onset": {
    "_unit": "minutes",
    "Oral": "15-45",
    "Vapourized": "2-10"
  },
  "links": {
    "experiences": "https://www.erowid.org/experiences/subs/exp_AH7921.shtml"
  },
  "name": "ah-7921",
  "pretty_name": "AH-7921",
  "properties": {
    "after-effects": "1-6 hours.",
    "aliases": [
      "ah7921"
    ],
    "categories": [
      "opioid",
      "research-chemical",
      "habit-forming",
      "depressant"
    ],
    "dose": "Oral Light: 10-20mg Common: 20-40mg Strong: 40mg+ Vapourized Light: 5-10mg Common: 10-25mg Strong: 25mg+",
    "duration": "Oral: 6-8 hours | Vapourized 3-4 hours.",
    "effects": "Euphoria, Dry Mouth, Mood lift, Itchiness, Relaxant, Constipation, Pupil constriction, Analgesia.",
    "onset": "Oral: 15-45 minutes. | Vapourized: 2-10 minutes.",
    "summary": "Opioid analgesic that is selective for the μ-opioid receptor. It has around 80% the potency of Morphine when taken orally."
  }
}

=== TripSit/drugs/src/data/dipt.json
{
  "aliases": [
    "diisopropyltryptamine"
  ],
  "categories": [
    "psychedelic",
    "research-chemical"
  ],
  "dose_note": " NOTE: This is a very new substance with very little history of human use. It is recommended to start low and increase dosage slowly. The dosages given are tentative, further research is recommended and caution is advised.",
  "formatted_aftereffects": {
    "_unit": "hours",
    "value": "12-24"
  },
  "formatted_dose": {
    "Oral": {
      "Common": "30-50mg",
      "Heavy": "50mg+",
      "Light": "15-25mg",
      "Threshold": "15mg"
    }
  },
  "formatted_duration": {
    "_unit": "hours",
    "value": "3-5"
  },
  "formatted_effects": [
    "Euphoria",
    "empathy",
    "insight",
    "brightened colour",
    "Closed/Open eye visuals",
    "enhanced tactile sensation",
    "mental/physical stimulation",
    "decreased appetite",
    "pupil dilation",
    "restlessness",
    "change in perception",
    "ego softening",
    "sweating/chills",
    "muscle tension",
    "confusion",
    "insomnia"
  ],
  "formatted_onset": {
    "_unit": "minutes",
    "value": "30-60"
  },
  "links": {
    "experiences": "https://www.erowid.org/experiences/subs/exp_DiPT.shtml",
    "tihkal": "https://www.erowid.org/library/books_online/tihkal/tihkal04.shtml"
  },
  "name": "dipt",
  "pretty_name": "DiPT",
  "properties": {
    "after-effects": "12-24 hours",
    "aliases": [
      "diisopropyltryptamine"
    ],
    "categories": [
      "psychedelic",
      "research-chemical"
    ],
    "dose": "Threshold: 15mg Light: 15-25mg Common: 30-50mg Heavy: 50mg+ | NOTE: This is a very new substance with very little history of human use. It is recommended to start low and increase dosage slowly. The dosages given are tentative, further research is recommended and caution is advised.",
    "duration": "3-5 hours",
    "effects": "Euphoria, empathy, insight, brightened colour, Closed/Open eye visuals, enhanced tactile sensation, mental/physical stimulation, decreased appetite, pupil dilation, restlessness, change in perception, ego softening, sweating/chills, muscle tension, confusion, insomnia.",
    "onset": "30-60 minutes.",
    "summary": "A rare psychedelic tryptamine closely related to DMT, with the interesting property of having little visual hallucinations, but strong auditory effects."
  },
  "pweffects": {
    "Auditory distortion": "https://psychonautwiki.org/wiki/Auditory_distortion",
    "Auditory enhancement": "https://psychonautwiki.org/wiki/Auditory_enhancement",
    "Auditory hallucinations": "https://psychonautwiki.org/wiki/Auditory_hallucinations",
    "Depersonalization": "https://psychonautwiki.org/wiki/Depersonalization",
    "Drifting": "https://psychonautwiki.org/wiki/Drifting",
    "Inner ear pressure": "https://psychonautwiki.org/wiki/Inner_ear_pressure",
    "Motor control loss": "https://psychonautwiki.org/wiki/Motor_control_loss",
    "Stomach bloating": "https://psychonautwiki.org/wiki/Stomach_bloating",
    "Thought suppression": "https://psychonautwiki.org/wiki/Thought_suppression"
  }
}

=== TripSit/drugs/src/data/4-aco-dmt.json
{
  "aliases": [
    "4acodmt",
    "psilacetin",
    "4-aco",
    "4-acetoxy-dmt"
  ],
  "categories": [
    "psychedelic",
    "research-chemical",
    "common"
  ],
  "formatted_aftereffects": {
    "_unit": "hours",
    "value": "1-12"
  },
  "formatted_dose": {
    "Oral": {
      "Common": "10-25mg",
      "Heavy": "25-40mg",
      "Light": "5-10mg"
    }
  },
  "formatted_duration": {
    "_unit": "hours",
    "value": "4-8"
  },
  "formatted_effects": [
    "4-aco-dmt is a psilocin analog",
    "so effects are very similar to mushrooms",
    "Some users report very little difference between 4-aco-dmt and psilocybin mushrooms"
  ],
  "formatted_onset": {
    "_unit": "minutes",
    "value": "20-90"
  },
  "links": {
    "experiences": "https://www.erowid.org/experiences/subs/exp_4AcODMT.shtml"
  },
  "name": "4-aco-dmt",
  "pretty_name": "4-AcO-DMT",
  "properties": {
    "after-effects": "1-12 hours.",
    "aliases": [
      "4acodmt",
      "psilacetin",
      "4-aco",
      "4-acetoxy-dmt"
    ],
    "categories": [
      "psychedelic",
      "research-chemical",
      "common"
    ],
    "comeup": "Slow comeup, some users report it taking nearly 2 hours until first effects are felt.",
    "dose": "Oral Light: 5-10mg Common: 10-25mg Heavy: 25-40mg",
    "duration": "4-8 hours.",
    "effects": "4-aco-dmt is a psilocin analog, so effects are very similar to Psilocybin mushrooms. Some users report very little difference between 4-aco-dmt and Psilocybin mushrooms.",
    "onset": "20-90 minutes. (dependant on form and stomach contents)",
    "summary": "A prodrug for Psilocin with extremely similar effects as Psilocybin Mushrooms."
  },
  "pweffects": {
    "8B Geometry - Exposure to inner mechanics of consciousness": "https://psychonautwiki.org/wiki/8B_Geometry_-_Exposure_to_inner_mechanics_of_consciousness",
    "Acuity enhancement": "https://psychonautwiki.org/wiki/Acuity_enhancement",
    "After images": "https://psychonautwiki.org/wiki/After_images",
    "Analysis enhancement": "https://psychonautwiki.org/wiki/Analysis_enhancement",
    "Auditory distortion": "https://psychonautwiki.org/wiki/Auditory_distortion",
    "Auditory enhancement": "https://psychonautwiki.org/wiki/Auditory_enhancement",
    "Auditory hallucinations": "https://psychonautwiki.org/wiki/Auditory_hallucinations",
    "Autonomous entities": "https://psychonautwiki.org/wiki/Autonomous_entities",
    "Colour enhancement": "https://psychonautwiki.org/wiki/Colour_enhancement",
    "Colour shifting": "https://psychonautwiki.org/wiki/Colour_shifting",
    "Conceptual thinking": "https://psychonautwiki.org/wiki/Conceptual_thinking",
    "Creativity enhancement": "https://psychonautwiki.org/wiki/Creativity_enhancement",
    "Déjà vu": "https://psychonautwiki.org/wiki/D%C3%A9j%C3%A0_vu",
    "Delusions": "https://psychonautwiki.org/wiki/Delusions",
    "Drifting": "https://psychonautwiki.org/wiki/Drifting",
    "Emotion enhancement": "https://psychonautwiki.org/wiki/Emotion_enhancement",
    "Enhancement and suppression cycles": "https://psychonautwiki.org/wiki/Enhancement_and_suppression_cycles",
    "Excessive yawning": "https://psychonautwiki.org/wiki/Excessive_yawning",
    "Exposure to inner mechanics of consciousness": "https://psychonautwiki.org/wiki/Exposure_to_inner_mechanics_of_consciousness",
    "External hallucinations": "https://psychonautwiki.org/wiki/External_hallucinations",
    "Feelings of impending doom": "https://psychonautwiki.org/wiki/Feelings_of_impending_doom",
    "Feelings of interdependent opposites": "https://psychonautwiki.org/wiki/Feelings_of_interdependent_opposites",
    "Feelings of predeterminism": "https://psychonautwiki.org/wiki/Feelings_of_predeterminism",
    "Feelings of self-design": "https://psychonautwiki.org/wiki/Feelings_of_self-design",
    "Geometry": "https://psychonautwiki.org/wiki/Geometry",
    "Immersion enhancement": "https://psychonautwiki.org/wiki/Immersion_enhancement",
    "Internal hallucinations": "https://psychonautwiki.org/wiki/Internal_hallucinations",
    "Machinescapes": "https://psychonautwiki.org/wiki/Machinescapes",
    "Memory suppression": "https://psychonautwiki.org/wiki/Memory_suppression",
    "Mindfulness": "https://psychonautwiki.org/wiki/Mindfulness",
    "Novelty enhancement": "https://psychonautwiki.org/wiki/Novelty_enhancement",
    "Pattern recognition enhancement": "https://psychonautwiki.org/wiki/Pattern_recognition_enhancement",
    "Personal bias suppression": "https://psychonautwiki.org/wiki/Personal_bias_suppression",
    "Personal meaning enhancement": "https://psychonautwiki.org/wiki/Personal_meaning_enhancement",
    "Perspective alterations": "https://psychonautwiki.org/wiki/Perspective_alterations",
    "Pupil dilation": "https://psychonautwiki.org/wiki/Pupil_dilation",
    "Rejuvenation": "https://psychonautwiki.org/wiki/Rejuvenation",
    "Runny nose": "https://psychonautwiki.org/wiki/Runny_nose",
    "Salivation": "https://psychonautwiki.org/wiki/Salivation",
    "Scenarios and plots": "https://psychonautwiki.org/wiki/Scenarios_and_plots",
    "Scenery slicing": "https://psychonautwiki.org/wiki/Scenery_slicing",
    "Sedation": "https://psychonautwiki.org/wiki/Sedation",
    "Settings, sceneries, and landscapes": "https://psychonautwiki.org/wiki/Settings,_sceneries,_and_landscapes",
    "Spirituality enhancement": "https://psychonautwiki.org/wiki/Spirituality_enhancement",
    "Spontaneous tactile sensations": "https://psychonautwiki.org/wiki/Spontaneous_tactile_sensations",
    "Subconscious communication": "https://psychonautwiki.org/wiki/Subconscious_communication",
    "Symmetrical texture repetition": "https://psychonautwiki.org/wiki/Symmetrical_texture_repetition",
    "Synaesthesia": "https://psychonautwiki.org/wiki/Synaesthesia",
    "Teeth grinding": "https://psychonautwiki.org/wiki/Teeth_grinding",
    "Temperature regulation suppression": "https://psychonautwiki.org/wiki/Temperature_regulation_suppression"
  }
}

=== TripSit/drugs/src/data/mdea.json
{
  "aliases": [
    "mde",
    "eve"
  ],
  "categories": [
    "stimulant",
    "empathogen",
    "tentative"
  ],
  "formatted_aftereffects": {
    "_unit": "hours",
    "value": "1-36"
  },
  "formatted_dose": {
    "Oral": {
      "Common": "100-150mg",
      "Light": "80-100mg",
      "Strong": "150-200mg."
    }
  },
  "formatted_duration": {
    "_unit": "hours",
    "value": "3-6"
  },
  "formatted_onset": {
    "_unit": "minutes",
    "value": "30-60"
  },
  "name": "mdea",
  "pretty_name": "MDEA",
  "properties": {
    "after-effects": "1-36 hours.",
    "aliases": [
      "mde",
      "eve"
    ],
    "categories": [
      "stimulant",
      "empathogen",
      "tentative"
    ],
    "dose": "Light: 80-100mg Common: 100-150mg Strong: 150-200mg.",
    "duration": "3-6 hours.",
    "onset": "30-60 minutes.",
    "summary": "A rare empathogen structurally related to MDMA. The drug is reportedly less potent than MDMA."
  }
}

=== TripSit/drugs/src/data/5-meo-malt.json
{
  "categories": [
    "psychedelic",
    "research-chemical"
  ],
  "dose_note": " NOTE: There are inconsistent reports on the drugs effects. It is recommended to start low and raise dosages slowly.",
  "formatted_dose": {
    "Insufflated": {
      "Common": "10-20mg",
      "Light": "5-10mg",
      "Strong": "20mg+"
    },
    "Oral": {
      "Common": "25-50mg",
      "Light": "15-25mg",
      "Strong": "50mg+"
    },
    "Vapourized": {
      "Common": "10-15mg",
      "Light": "5-10mg",
      "Strong": "15-20mg"
    }
  },
  "formatted_duration": {
    "_unit": "hours",
    "Insufflated": "1-3",
    "Oral": "2-4",
    "Vapourized": "0.5-1.5"
  },
  "formatted_effects": [
    "Euphoria",
    "empathy",
    "insight",
    "brightened colour",
    "Closed/Open eye visuals",
    "enhanced tactile sensation",
    "mental/physical stimulation",
    "decreased appetite",
    "pupil dilation",
    "restlessness",
    "change in perception",
    "ego softening",
    "sweating/chills",
    "muscle tension",
    "confusion",
    "insomnia"
  ],
  "formatted_onset": {
    "_unit": "minutes",
    "Insufflated": "5-15",
    "Oral": "5-30",
    "Vapourized": "1-5"
  },
  "name": "5-meo-malt",
  "pretty_name": "5-MeO-MALT",
  "properties": {
    "categories": [
      "psychedelic",
      "research-chemical"
    ],
    "dose": "Oral Light: 15-25mg Common: 25-50mg Strong: 50mg+ | Insufflated Light: 5-10mg Common: 10-20mg Strong: 20mg+ | Vapourized Light: 5-10mg Common: 10-15mg Strong: 15-20mg | There are inconsistent reports on the drugs effects. It is recommended to start low and raise dosages slowly.",
    "duration": "Oral: 2-4 hours. | Insufflated: 1-3 hours. | Vapourized: 0.5-1.5 hours.",
    "effects": "Euphoria, empathy, insight, brightened colour, Closed/Open eye visuals, enhanced tactile sensation, mental/physical stimulation, decreased appetite, pupil dilation, restlessness, change in perception, ego softening, sweating/chills, muscle tension, confusion, insomnia.",
    "onset": "Oral: 5-30 minutes. | Insufflated: 5-15 minutes. | Vapourized: 1-5 minutes.",
    "summary": "A new and uncommon psychedelic tryptamine related to 5-MeO-DALT. Little is known about the drug, however its effects are likely similar to other psychedelic tryptamines."
  }
}

=== TripSit/drugs/src/data/thiopropamine.json
{
  "aliases": [
    "tpa",
    "normethiopropamine",
    "a-methyl-2-thipheneethanamine"
  ],
  "categories": [
    "stimulant",
    "habit-forming",
    "research-chemical"
  ],
  "formatted_aftereffects": {
    "_unit": "hours",
    "Insufflated": "1-2",
    "Oral": "1-3"
  },
  "formatted_dose": {
    "Oral": {
      "Common": "50-100mg",
      "Light": "20-50mg",
      "Strong": "100-125mg+"
    }
  },
  "formatted_duration": {
    "_unit": "hours",
    "Insufflated": "1-2",
    "Oral": "1-4"
  },
  "formatted_onset": {
    "_unit": "minutes",
    "Insufflated": "5-15",
    "Oral": "15-45"
  },
  "name": "thiopropamine",
  "pretty_name": "Thiopropamine",
  "properties": {
    "after-effects": "Oral: 1-3 hours | Insufflated: 1-2 hours.",
    "aliases": [
      "tpa",
      "normethiopropamine",
      "a-methyl-2-thipheneethanamine"
    ],
    "categories": [
      "stimulant",
      "habit-forming",
      "research-chemical"
    ],
    "dose": "Oral Light: 20-50mg Common: 50-100mg Strong: 100-125mg+",
    "duration": "Oral: 1-4 hours. | Insufflated: 1-2 hours.",
    "onset": "Oral: 15-45 minutes. | Insufflated: 5-15mg.",
    "summary": "A substance that is closely related to methiopopramine (MPA). Is roughly about 1/3rd the potency of amphetamine and differs from amphetmine from the phenyl ring in which it is switched with a thiophene ring."
  }
}

=== TripSit/drugs/src/data/2-ai.json
{
  "aliases": [
    "2ai",
    "2-aminoindan"
  ],
  "categories": [
    "stimulant",
    "research-chemical",
    "habit-forming",
    "tentative"
  ],
  "formatted_aftereffects": {
    "_unit": "hours",
    "value": "2-4"
  },
  "formatted_dose": {
    "Oral": {
      "Common": "10-20mg",
      "Light": "5-10mg",
      "Strong": "20-40mg+",
      "Threshold": "3-5mg"
    }
  },
  "formatted_duration": {
    "_unit": "hours",
    "value": "1-2"
  },
  "formatted_effects": [
    "Euphoria",
    "increased energy/alertness",
    "decreased need for sleep",
    "increased sociability",
    "mood lift",
    "increased libido",
    "excessive talking",
    "decreased appetite",
    "weight loss",
    "sweating",
    "disturbed sleep patterns",
    "bruxism",
    "visual and auditory hallucinations",
    "itchiness",
    "aggressiveness",
    "moodiness"
  ],
  "formatted_onset": {
    "_unit": "minutes",
    "value": "10-30"
  },
  "links": {
    "experiences": "https://www.erowid.org/experiences/subs/exp_2Aminoindan.shtml"
  },
  "name": "2-ai",
  "pretty_name": "2-AI",
  "properties": {
    "after-effects": "2-4 hours",
    "aliases": [
      "2ai",
      "2-aminoindan"
    ],
    "categories": [
      "stimulant",
      "research-chemical",
      "habit-forming",
      "tentative"
    ],
    "dose": "Oral Threshold: 3-5mg Light: 5-10mg Common: 10-20mg Strong: 20-40mg+",
    "duration": "1-2 hours.",
    "experiences": "https://www.erowid.org/experiences/subs/exp_2Aminoindan.shtml",
    "half-life": "1-2 hours.",
    "onset": "10-30 minutes",
    "summary": "Short-acting stimulant that is sometimes compared to the likes of Methamphetamine. It is a rigid analogue of Amphetamine, and also partially substitutes for the prior in rat discrimination studies.",
    "test-kits": "Marquis: Orange > Brown. | Mecke: Yellow. | Mandelin: Blue. | Liebermann: Yellow Brown. | Ehrlich: No colour change."
  },
  "pweffects": {
    "Acuity enhancement": "https://psychonautwiki.org/wiki/Acuity_enhancement",
    "Analysis enhancement": "https://psychonautwiki.org/wiki/Analysis_enhancement",
    "Anxiety": "https://psychonautwiki.org/wiki/Anxiety",
    "Appetite suppression": "https://psychonautwiki.org/wiki/Appetite_suppression",
    "Cognitive euphoria": "https://psychonautwiki.org/wiki/Cognitive_euphoria",
    "Cognitive fatigue": "https://psychonautwiki.org/wiki/Cognitive_fatigue",
    "Compulsive redosing": "https://psychonautwiki.org/wiki/Compulsive_redosing",
    "Dehydration": "https://psychonautwiki.org/wiki/Dehydration",
    "Depression": "https://psychonautwiki.org/wiki/Depression",
    "Focus enhancement": "https://psychonautwiki.org/wiki/Focus_enhancement",
    "Increased heart rate": "https://psychonautwiki.org/wiki/Increased_heart_rate",
    "Increased perspiration": "https://psychonautwiki.org/wiki/Increased_perspiration",
    "Irritability": "https://psychonautwiki.org/wiki/Irritability",
    "Memory enhancement": "https://psychonautwiki.org/wiki/Memory_enhancement",
    "Motivation enhancement": "https://psychonautwiki.org/wiki/Motivation_enhancement",
    "Nausea": "https://psychonautwiki.org/wiki/Nausea",
    "Pain relief": "https://psychonautwiki.org/wiki/Pain_relief",
    "Stimulation": "https://psychonautwiki.org/wiki/Stimulation",
    "Teeth grinding": "https://psychonautwiki.org/wiki/Teeth_grinding",
    "Temporary erectile dysfunction": "https://psychonautwiki.org/wiki/Temporary_erectile_dysfunction",
    "Thought acceleration": "https://psychonautwiki.org/wiki/Thought_acceleration",
    "Thought deceleration": "https://psychonautwiki.org/wiki/Thought_deceleration",
    "Wakefulness": "https://psychonautwiki.org/wiki/Wakefulness"
  }
}
