=== TripSit/drugs/schemas/drug-schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "Drug",
  "type": "object",
  "additionalProperties": false,
  "required": ["name", "pretty_name", "properties"],
  "properties": {
    "aliases": { "type": "array", "items": { "type": "string" } },
    "categories": { "type": "array", "items": { "$ref": "#/definitions/Category" } },
    "formatted_aftereffects": { "$ref": "#/definitions/Duration" },
    "formatted_dose": { "$ref": "#/definitions/Dose" },
    "formatted_duration": { "$ref": "#/definitions/Duration" },
    "formatted_effects": { "type": "array", "items": { "type": "string" } },
    "formatted_onset": { "$ref": "#/definitions/Duration" },
    "links": { "$ref": "#/definitions/Links" },
    "name": { "type": "string" },
    "pretty_name": { "type": "string" },
    "properties": { "$ref": "#/definitions/Properties" },
    "pweffects": { "type": "object", "additionalProperties": { "type": "string", "format": "uri" } },
    "dose_note": { "type": "string" },
    "sources": { "$ref": "#/definitions/Sources" }
  },
  "definitions": {
    "Category": {
      "type": "string",
      "enum": ["depressant","habit-forming","tentative","research-chemical","psychedelic","stimulant","dissociative","inactive","empathogen","common","benzodiazepine","opioid","supplement","nootropic","barbiturate","deliriant","ssri"],
      "title": "Category"
    },
    "Dose": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "Oral": { "$ref": "#/definitions/Dosage" },
        "Insufflated": { "$ref": "#/definitions/Dosage" },
        "Rectal": { "$ref": "#/definitions/Dosage" },
        "Vapourized": { "$ref": "#/definitions/Dosage" },
        "Intravenous": { "$ref": "#/definitions/Dosage" },
        "Smoked": { "$ref": "#/definitions/Dosage" },
        "Sublingual": { "$ref": "#/definitions/Dosage" },
        "Buccal": { "$ref": "#/definitions/Dosage" },
        "Intramuscular": { "$ref": "#/definitions/Dosage" },
        "Transdermal": { "$ref": "#/definitions/Dosage" },
        "HBWR": { "$ref": "#/definitions/Dosage" },
        "Morning_Glory": { "$ref": "#/definitions/Dosage" },
        "Dried": { "$ref": "#/definitions/Dosage" },
        "Fresh": { "$ref": "#/definitions/Dosage" },
        "Insufflated(Pure)": { "$ref": "#/definitions/Dosage" },
        "Oral(Benzedrex)": { "$ref": "#/definitions/Dosage" },
        "Oral(Pure)": { "$ref": "#/definitions/Dosage" },
        "Dry": { "$ref": "#/definitions/Dosage" },
        "Wet": { "$ref": "#/definitions/Dosage" }
      },
      "title": "Dose"
    },
    "Dosage": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "Common": { "type": "string" },
        "Light": { "type": "string" },
        "Strong": { "type": "string" },
        "Threshold": { "type": "string" },
        "Heavy": { "type": "string" },
        "Dangerous": { "type": "string" },
        "Fatal": { "type": "string" },
        "Note": { "type": "string" }
      },
      "title": "Dosage"
    },
    "Duration": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "_unit": { "$ref": "#/definitions/Unit" },
        "value": { "type": "string" },
        "Insufflated": { "type": "string" },
        "Oral": { "type": "string" },
        "Rectal": { "type": "string" },
        "Vapourized": { "type": "string" },
        "Smoked": { "type": "string" },
        "Oral_ER": { "type": "string" },
        "Oral_IR": { "type": "string" },
        "Intramuscular": { "type": "string" },
        "Intravenous": { "type": "string" },
        "Metabolites": { "type": "string" },
        "Parent": { "type": "string" },
        "Oral_MAOI": { "type": "string" },
        "Buccal": { "type": "string" },
        "Transdermal": { "type": "string" },
        "Sublingual": { "type": "string" },
        "Insufflated_IR": { "type": "string" },
        "Insufflated_XR": { "type": "string" }
      },
      "title": "Duration"
    },
    "Links": {
      "type": "object",
      "additionalProperties": false,
      "required": ["experiences"],
      "properties": {
        "experiences": { "type": "string", "format": "uri" },
        "pihkal": { "type": "string", "format": "uri" },
        "tihkal": { "type": "string", "format": "uri" }
      },
      "title": "Links"
    },
    "Properties": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "after-effects": { "type": "string" },
        "aliases": { "type": "array", "items": { "type": "string" } },
        "avoid": { "type": "string" },
        "categories": { "type": "array", "items": { "$ref": "#/definitions/Category" } },
        "dose": { "type": "string" },
        "duration": { "type": "string" },
        "half-life": { "type": "string" },
        "onset": { "type": "string" },
        "summary": { "type": "string" },
        "test-kits": { "type": "string" },
        "experiences": { "type": "string", "format": "uri" },
        "warning": { "type": "string" },
        "marquis": { "type": "string" },
        "effects": { "type": "string" },
        "risks": { "type": "string" },
        "comeup": { "type": "string" },
        "note": { "type": "string" },
        "detection": { "type": "string" },
        "wiki": { "type": "string", "format": "uri" },
        "mdma": { "type": "string" },
        "tolerance": { "type": "string" },
        "bioavailability": { "type": "string" },
        "dose_to_diazepam": { "type": "string" },
        "adverse-effects": { "type": "string" },
        "chemistry": { "type": "string" },
        "contraindications": { "type": "string" },
        "legal": { "type": "string" },
        "overdose-symptoms": { "type": "string" },
        "pharmacokinetics": { "type": "string" },
        "pharmacology": { "type": "string" },
        "obtain": { "type": "string" },
        "pharmacodynamics": { "type": "string" },
        "side-effects": { "type": "string" },
        "molecule": { "type": "string", "format": "uri" },
        "vaporization": { "type": "string" },
        "calculator": { "type": "string", "format": "uri" },
        "chart": { "type": "string", "format": "uri" },
        "Oral": { "type": "string" },
        "general-advice": { "type": "string" },
        "potentiators": { "type": "string" }
      },
      "title": "Properties"
    },
    "Sources": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "_general": { "type": "array", "items": { "type": "string" } },
        "dose": { "type": "array", "items": { "type": "string", "format": "uri" } },
        "duration": { "type": "array", "items": { "type": "string", "format": "uri" } },
        "bioavailability": { "type": "array", "items": { "type": "string", "format": "uri" } },
        "legality": { "type": "array", "items": { "type": "string", "format": "uri" } },
        "onset": { "type": "array", "items": { "type": "string" } }
      },
      "title": "Sources"
    },
    "Unit": {
      "type": "string",
      "enum": ["hours", "minutes"],
      "title": "Unit"
    }
  }
}

=== TripSit/drugs/src/data/5-meo-amt.json
{
  "aliases": [
    "5meoamt"
  ],
  "categories": [
    "stimulant",
    "psychedelic",
    "research-chemical",
    "empathogen"
  ],
  "dose_note": " NOTE: Hospitalizations have occured with as doses as low as 8mg",
  "formatted_aftereffects": {
    "_unit": "hours",
    "value": "4-24+"
  },
  "formatted_dose": {
    "Oral": {
      "Common": "2-4mg",
      "Light": "1-2mg",
      "Strong": "4-6mg",
      "Threshold": "0.5-1mg"
    }
  },
  "formatted_duration": {
    "_unit": "hours",
    "Insufflated": "8-12",
    "Oral": "12-18"
  },
  "formatted_effects": [
    "Euphoria",
    "empathy",
    "insight",
    "brightened colour",
    "Closed/Open eye visuals",
    "enhanced tactile sensation",
    "mental/physical stimulation",
    "decreased appetite",
    "pupil dilation",
    "restlessness",
    "change in perception",
    "ego softening",
    "sweating/chills",
    "muscle tension",
    "confusion",
    "insomnia"
  ],
  "formatted_onset": {
    "_unit": "minutes",
    "value": "30-120"
  },
  "links": {
    "experiences": "https://www.erowid.org/experiences/subs/exp_5MeOAMT.shtml"
  },
  "name": "5-meo-amt",
  "pretty_name": "5-MeO-αMT",
  "properties": {
    "after-effects": "4-24+ hours.",
    "aliases": [
      "5meoamt"
    ],
    "categories": [
      "stimulant",
      "psychedelic",
      "research-chemical",
      "empathogen"
    ],
    "dose": "Oral Threshold: 0.5-1mg Light: 1-2mg Common: 2-4mg Strong: 4-6mg | NOTE: Hospitalizations have occured with as doses as low as 8mg",
    "duration": "Oral: 12-18 hours. | Insufflated: 8-12 hours.",
    "effects": "Euphoria, empathy, insight, brightened colour, Closed/Open eye visuals, enhanced tactile sensation, mental/physical stimulation, decreased appetite, pupil dilation, restlessness, change in perception, ego softening, sweating/chills, muscle tension, confusion, insomnia.",
    "onset": "30-120 minutes.",
    "summary": "A long-acting psychedelic and entactogenic tryptamine. The drug is structurally related to aMT. The drug is reported to be very potent and is sometimes sold on blotters. There have been a few reports of the drug being sold as LSD, however it seems this is rare. The drug may be an MAOI, caution is advised when dosing."
  }
}

=== TripSit/drugs/src/data/lormetazepam.json
{
  "aliases": [
    "noctamid"
  ],
  "categories": [
    "benzodiazepine",
    "depressant",
    "habit-forming"
  ],
  "formatted_aftereffects": {
    "_unit": "hours",
    "value": "1-24"
  },
  "formatted_dose": {
    "Oral": {
      "Common": "1-2mg",
      "Light": "0.5-1mg",
      "Strong": "2-4mg."
    }
  },
  "formatted_duration": {
    "_unit": "hours",
    "value": "4-8"
  },
  "formatted_onset": {
    "_unit": "minutes",
    "value": "10-30"
  },
  "name": "lormetazepam",
  "pretty_name": "Lormetazepam",
  "properties": {
    "after-effects": "1-24 hours depending on dosages",
    "aliases": [
      "noctamid"
    ],
    "avoid": "All other CNS depressants.",
    "bioavailability": "Oral: 80%.",
    "categories": [
      "benzodiazepine",
      "depressant",
      "habit-forming"
    ],
    "dose": "Light: 0.5-1mg Common: 1-2mg Strong: 2-4mg.",
    "dose_to_diazepam": "Lormetazepam - 1-2mg's ~=10mg Diazepam.",
    "duration": "4-8 hours depending on dosages",
    "onset": "10-30 minutes.",
    "summary": "The drug is a less commonly prescribed benzodiazepine. The drug is short-acting with a short half-life. The drug is typically seen in the Netherlands. The drug is reported to have sedative, hypnotic, and anxiolytic effects."
  }
}

=== TripSit/drugs/src/data/am-2201.json
{
  "aliases": [
    "am2201"
  ],
  "categories": [
    "research-chemical",
    "tentative",
    "habit-forming"
  ],
  "formatted_aftereffects": {
    "_unit": "minutes",
    "value": "15-60"
  },
  "formatted_dose": {
    "Vapourized": {
      "Common": "500-1000ug",
      "Light": "250-500ug",
      "Strong": "1000-2000ug"
    }
  },
  "formatted_duration": {
    "_unit": "minutes",
    "Oral": "60-180",
    "Vapourized": "30-90"
  },
  "formatted_onset": {
    "_unit": "minutes",
    "Oral": "15-30",
    "Vapourized": "1-3"
  },
  "name": "am-2201",
  "pretty_name": "AM-2201",
  "properties": {
    "after-effects": "15-60 minutes.",
    "aliases": [
      "am2201"
    ],
    "categories": [
      "research-chemical",
      "tentative",
      "habit-forming"
    ],
    "dose": "Vapourized Light: 250-500ug Common: 500-1000ug Strong: 1000-2000ug",
    "duration": "Vapourized: 30-90 minutes. | Oral: 60-180 minutes.",
    "onset": "Vapourized: 1-3 minutes. | Oral: 15-30 minutes.",
    "summary": "A synthetic cannabanoid that is very potent. Active doses start at around 250ug's. It is recommended to be cautious with this substance. It has also been noted that it can cause convulsions."
  }
}

=== TripSit/drugs/src/data/ethylphenidate.json
{
  "aliases": [
    "eph"
  ],
  "categories": [
    "stimulant",
    "research-chemical",
    "habit-forming",
    "common"
  ],
  "dose_note": " NOTE: Ethylphenidate should NOT be insufflated as it is known to be highly caustic and will cause serious harm to the nasal septum, even with light usage. This drug reacts with users in varying ways, it is recommended to start low and increase dosages slowly.",
  "formatted_aftereffects": {
    "_unit": "hours",
    "value": "1-12"
  },
  "formatted_dose": {
    "Oral": {
      "Common": "40-100mg",
      "Heavy": "150-200mg",
      "Light": "20-40mg",
      "Strong": "100-150mg"
    },
    "Rectal": {
      "Common": "15-30mg",
      "Heavy": "50-75mg",
      "Light": "5-15mg",
      "Strong": "30-50mg"
    }
  },
  "formatted_duration": {
    "_unit": "hours",
    "Insufflated": "2-6",
    "Oral": "4-10",
    "Rectal": "2-6"
  },
  "formatted_effects": [
    "Focus/mental clarity",
    "Abstract thinking",
    "Euphoria",
    "Stimulation",
    "Increased music appreciation",
    "Warm fuzzy body high",
    "Increased desire to talk",
    "Wakefulness",
    "increased sex drive",
    "Chest pain",
    "Vasoconstriction",
    "Jaw Tension",
    "Restlessness",
    "high blood pressure",
    "compulsion to redose",
    "paranoia"
  ],
  "formatted_onset": {
    "_unit": "minutes",
    "Insufflated": "1-10",
    "Oral": "45-120",
    "Rectal": "5-20"
  },
  "links": {
    "experiences": "https://www.erowid.org/experiences/subs/exp_Ethylphenidate.shtml"
  },
  "name": "ethylphenidate",
  "pretty_name": "Ethylphenidate",
  "properties": {
    "after-effects": "1-12 hours.",
    "aliases": [
      "eph"
    ],
    "categories": [
      "stimulant",
      "research-chemical",
      "habit-forming",
      "common"
    ],
    "dose": "Oral Light: 20-40mg Common: 40-100mg Strong: 100-150mg Heavy: 150-200mg | Rectal Light: 5-15mg Common: 15-30mg Strong: 30-50mg Heavy: 50-75mg | NOTE: Ethylphenidate should NOT be insufflated (see summary for more details). This drug reacts with users in varying ways, so start low and work your way up.",
    "duration": "Oral: 4-10 hours. | Insufflated: 2-6 hours. | Plugged: 2-6 hours.",
    "effects": "Focus/mental clarity, Abstract thinking, Euphoria, Stimulation, Increased music appreciation, Warm fuzzy body high, Increased desire to talk, Wakefulness, increased sex drive, Chest pain, Vasoconstriction, Jaw Tension, Restlessness, high blood pressure, compulsion to redose, paranoia",
    "onset": "Insufflated: 1-10 minutes | Plugged: 5-20 minutes | Oral: 45-120 minutes",
    "summary": "Potent psychostimulant, similar to Methylphenidate. Note: Ethylphenidate should NOT be insufflated as it is known to be highly caustic and will cause serious harm to your nasal septum, even with light usage."
  },
  "pweffects": {
    "Analysis enhancement": "https://psychonautwiki.org/wiki/Analysis_enhancement",
    "Anxiety": "https://psychonautwiki.org/wiki/Anxiety",
    "Appetite suppression": "https://psychonautwiki.org/wiki/Appetite_suppression",
    "Cognitive euphoria": "https://psychonautwiki.org/wiki/Cognitive_euphoria",
    "Cognitive fatigue": "https://psychonautwiki.org/wiki/Cognitive_fatigue",
    "Dehydration": "https://psychonautwiki.org/wiki/Dehydration",
    "Depression": "https://psychonautwiki.org/wiki/Depression",
    "Empathy, love, and sociability enhancement": "https://psychonautwiki.org/wiki/Empathy,_love,_and_sociability_enhancement",
    "Focus enhancement": "https://psychonautwiki.org/wiki/Focus_enhancement",
    "Increased heart rate": "https://psychonautwiki.org/wiki/Increased_heart_rate",
    "Irritability": "https://psychonautwiki.org/wiki/Irritability",
    "Motivation enhancement": "https://psychonautwiki.org/wiki/Motivation_enhancement",
    "Stimulation": "https://psychonautwiki.org/wiki/Stimulation",
    "Teeth grinding": "https://psychonautwiki.org/wiki/Teeth_grinding",
    "Thought acceleration": "https://psychonautwiki.org/wiki/Thought_acceleration",
    "Thought deceleration": "https://psychonautwiki.org/wiki/Thought_deceleration",
    "Vasoconstriction": "https://psychonautwiki.org/wiki/Vasoconstriction",
    "Wakefulness": "https://psychonautwiki.org/wiki/Wakefulness"
  },
  "sources": {
    "_general": [
      "https://www.ncbi.nlm.nih.gov/pubmed/10820132",
      "Ethylphenidate formation in human subjects after the administration of a single dose of methylphenidate and ethanol - https://www.ncbi.nlm.nih.gov/pubmed/10820132",
      "Methylphenidate and its ethanol transesterification metabolite ethylphenidate: brain disposition, monoamine transporters and motor activity - http://www.ncbi.nlm.nih.gov/pubmed/17218796"
    ]
  }
}

=== TripSit/drugs/src/data/estazolam.json
{
  "aliases": [
    "prosom",
    "eurodin",
    "elprazolam"
  ],
  "categories": [
    "benzodiazepine",
    "habit-forming",
    "depressant"
  ],
  "formatted_aftereffects": {
    "_unit": "hours",
    "value": "2-24"
  },
  "formatted_dose": {
    "Oral": {
      "Common": "1-2mg",
      "Light": "0.5-1mg",
      "Strong": "2-4mg+"
    }
  },
  "formatted_duration": {
    "_unit": "hours",
    "value": "7-12"
  },
  "formatted_effects": [
    "Anxiolytic",
    "Sedative",
    "Muscle Relaxant",
    "Amnesia",
    "Dystaxia",
    "Hypnotic"
  ],
  "formatted_onset": {
    "_unit": "minutes",
    "value": "30-60"
  },
  "name": "estazolam",
  "pretty_name": "Estazolam",
  "properties": {
    "after-effects": "2-24 hours.",
    "aliases": [
      "prosom",
      "eurodin",
      "elprazolam"
    ],
    "avoid": "All other CNS depressants.",
    "bioavailability": "Oral 93%",
    "categories": [
      "benzodiazepine",
      "habit-forming",
      "depressant"
    ],
    "dose": "Light: 0.5-1mg Common: 1-2mg Strong: 2-4mg+",
    "dose_to_diazepam": "Estazolam - 1-2mg's ~=10mg Diazepam.",
    "duration": "7-12 hours.",
    "effects": "Anxiolytic, Sedative, Muscle Relaxant, Amnesia, Dystaxia, Hypnotic.",
    "onset": "30-60 minutes.",
    "summary": "A rarely prescribed medium-duration prescription benzodiazepine. Mainly used as a hypnotic, it can cause amnesia and lowered inhibitions in higher dosages."
  }
}

=== TripSit/drugs/src/data/amt.json
{
  "aliases": [
    "Alpha-methyltryptamine",
    "alpha-methyltryptamine",
    "alphamethyltryptamine",
    "indopan",
    "monase"
  ],
  "categories": [
    "psychedelic",
    "stimulant",
    "research-chemical"
  ],
  "formatted_aftereffects": {
    "_unit": "hours",
    "value": "6-12"
  },
  "formatted_dose": {
    "Oral": {
      "Common": "25-40mg",
      "Heavy": "60mg+",
      "Light": "15-25mg",
      "Strong": "40-60mg"
    }
  },
  "formatted_duration": {
    "_unit": "hours",
    "value": "10-16"
  },
  "formatted_effects": [
    "Euphoria",
    "empathy",
    "insight",
    "brightened colour",
    "Closed/Open eye visuals",
    "enhanced tactile sensation",
    "mental/physical stimulation",
    "decreased appetite",
    "pupil dilation",
    "restlessness",
    "change in perception",
    "ego softening",
    "sweating/chills",
    "muscle tension",
    "confusion",
    "insomnia"
  ],
  "formatted_onset": {
    "_unit": "minutes",
    "value": "30-90"
  },
  "links": {
    "experiences": "https://www.erowid.org/experiences/subs/exp_AMT.shtml"
  },
  "name": "amt",
  "pretty_name": "αMT",
  "properties": {
    "after-effects": "6-12 hours",
    "aliases": [
      "Alpha-methyltryptamine",
      "alpha-methyltryptamine",
      "alphamethyltryptamine",
      "indopan",
      "monase"
    ],
    "avoid": "Other MAOIs http://www.erowid.org/chemicals/maois/maois_info3.shtml",
    "categories": [
      "psychedelic",
      "stimulant",
      "research-chemical"
    ],
    "detection": "Not tested for in standard drug tests.",
    "dose": "Oral Light: 15-25mg Common: 25-40mg Strong: 40-60mg Heavy: 60mg+",
    "duration": "10-16 hours",
    "effects": "Euphoria, empathy, insight, brightened colour, Closed/Open eye visuals, enhanced tactile sensation, mental/physical stimulation, decreased appetite, pupil dilation, restlessness, change in perception, ego softening, sweating/chills, muscle tension, confusion, insomnia.",
    "onset": "30-90 minutes",
    "summary": "A long-acting psychedelic-empathogen with a broad method of action in the brain. Not suitable for combination with many other substances. Used as an anti-depressant in the Soviet Union, but later found popularity in the RC scene, mainly in the UK."
  }
}

=== TripSit/drugs/src/data/homomazindol.json
{
  "categories": [
    "stimulant",
    "tentative",
    "research-chemical",
    "habit-forming"
  ],
  "name": "homomazindol",
  "pretty_name": "Homomazindol",
  "properties": {
    "categories": [
      "stimulant",
      "tentative",
      "research-chemical",
      "habit-forming"
    ],
    "summary": "A potent analogue of mazindol, a rare, atypical stimulant drug and appetite suppressant occasionally prescribed in cases of severe obesity."
  }
}

=== TripSit/drugs/src/data/3-ho-pcp.json
{
  "aliases": [
    "3hopcp"
  ],
  "categories": [
    "dissociative",
    "research-chemical",
    "habit-forming",
    "tentative"
  ],
  "formatted_aftereffects": {
    "_unit": "hours",
    "value": "2"
  },
  "formatted_dose": {
    "Oral": {
      "Common": "4-5mg",
      "Light": "2-4mg",
      "Strong": "5mg+"
    }
  },
  "formatted_duration": {
    "_unit": "hours",
    "value": "3-4"
  },
  "formatted_onset": {
    "_unit": "minutes",
    "value": "20-40"
  },
  "name": "3-ho-pcp",
  "pretty_name": "3-HO-PCP",
  "properties": {
    "after-effects": "2 hours to a month.",
    "aliases": [
      "3hopcp"
    ],
    "categories": [
      "dissociative",
      "research-chemical",
      "habit-forming",
      "tentative"
    ],
    "dose": "Oral Threshold: ~2mg Light: 2-4mg Common: 4-5mg Strong: 5+mg",
    "duration": "3-4 hours",
    "onset": "20-40 minutes",
    "summary": "An arylcyclohexamine dissociative analogue of PCP, this drug is relatively uncommon, and little information is available. It is reported to not only have dissociative activity but also opioid activity. Some trip reports suggest very negative side-effects including intense muscle tension."
  }
}
